[package]
name = "cbat"
version = "0.1.0"
edition = "2021"

[dependencies]
itsybitsy_m0 = "0.13.0"
panic-halt = "0.2"

[profile.release]
lto = true
opt-level = "s"

# for cargo flash
[package.metadata]
chip = "ATSAMD21G18A"
